BLUE_WIN_MESSAGE = "Blue wins!"
RED_WIN_MESSAGE = "Red wins!"
TIE_WIN_MESSAGE = "It's a tie!"

SIM_REPS = 10000

AUTO_LENGTH = 15
TELEOP_LENGTH = 135
ENDGAME_LENGTH = 30

AUTO_PAINTING_SCORE_VALUE = 20
PAINTING_SCORE_VALUE = 10
AUTO_STATUE_SCORE_VALUE = 10
STATUE_SCORE_VALUE = 5
CHAIN_PULL_SCORE_VALUE = 10
CHAIN_PULL_STATUE_ADDER = 5
SPRINKLER_BUTTON_VALUE = 2

RP_STATUES_REQUIRED = 4
FIRE_ALARM_RP = 1
STATUE_LIFT_RP = 1
TIE_RP = 1
WIN_RP = 2

ALARM_1_PERIOD = 35
ALARM_2_PERIOD = 40
ALARM_3_PERIOD = 45
DEADZONE = 5
ALARM_TIME = 10

NEAR_STATUES = 2
FAR_STATUES = 2
LOW_PAINTINGS = 12
MID_PAINTINGS = 24
HIGH_PAINTINGS = 36
FLOOR_PAINTINGS = 0
CHAIN_PULL = 2

ROBOT_QUALITY_DISTRIBUTION = {
    "ELITE": 2,
    "ABOVE AVERAGE": 30,
    "AVERAGE": 45,
    "BELOW AVERAGE": 20,
    "NOT FUNCTIONAL": 3
}

ROBOT_STRATEGY_DISTRIBUTION = {
    "ALL BOT": 30,
    "PAINTINGS ONLY": 15,
    "STATUES ONLY": 15,
    "STATUES+LOW PAINTINGS": 15,
    "LOW PAINTINGS ONLY": 15,
    "CHASSIS BOT": 10
}